services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      APP_HTTP_ADDR: "${APP_HTTP_ADDR}"
      APP_DB_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
      APP_JWT_SECRET: "${APP_JWT_SECRET}"
      APP_ACCESS_TTL_MIN: "${APP_ACCESS_TTL_MIN}"
      APP_REFRESH_TTL_DAYS: "${APP_REFRESH_TTL_DAYS}"
      APP_CORS_ORIGINS: "${APP_CORS_ORIGINS}"
      APP_OSRM_BASE_URL: "${APP_OSRM_BASE_URL}"
    ports:
      - "8080:8080"

volumes:
  db_data:
